//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_Smarkets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int Id { get; set; }
        public string Paciente { get; set; }
        public string Data_Nascimento { get; set; }
        public string Medico { get; set; }
        public string Especialidade { get; set; }
        public string Data_Inicio_Cons { get; set; }
        public string Hora_Inicio_Cons { get; set; }
        public string Data_Fim_Cons { get; set; }
        public string Hora_Fim_Cons { get; set; }
        public string Observacao { get; set; }
    }
}
